# pytest.ini is a configuration file used by pytest to control how your tests run
# without having to type long command-line options again and again

; [pytest]
; testpaths = tests

; # This prevents pytest from giving you warnings about unknown markers.
; ; [pytest] 
; ; markers =
; ; login: Login related testcses
; ; checkout : Checkout related testcases

[pytest]
testpaths = tests # look for tests inside the test folder
python_files = test_*.py # according to this configured pattern,pytest will only look for files that start with test_ and end with .py 
python_functions = test_*
addopts = -v

markers =
    smoke: Critical application tests
    regression: Complete regression tests
    login: Login related tests
    cart: Cart related tests
    checkout: Checkout related tests
