# pytest.ini is the configuration file used by pytest
# to control how tests are executed.

[pytest]

# Look for tests inside the tests folder
testpaths = tests

# Test file naming pattern
python_files = test_*.py

# Test function naming pattern
python_functions = test_*

# Run pytest in verbose mode
addopts = -v

# Custom test markers
markers =
    smoke: Critical application tests
    regression: Complete regression tests
    login: Login related tests
    cart: Cart related tests
    checkout: Checkout related tests